"use client";
import {FormEvent,useMemo,useState} from "react";

type Scam={title:string;group:string;icon:string;desc:string;example:string;signs:string[];action:string;keys:string[]};
const S=(title:string,group:string,icon:string,desc:string,example:string,signs:string[],action:string,keys:string[]):Scam=>({title,group,icon,desc,example,signs,action,keys});
const scams:Scam[]=[
S("Tuyển dụng “việc nhẹ lương cao” làm nhiệm vụ bấm like, share hoặc đánh giá sản phẩm","Mạng & giả mạo","⚠️","Đối tượng mạo danh công ty truyền thông hoặc sàn thương mại điện tử, tiếp cận sinh viên qua Telegram, Zalo hoặc Facebook và mời làm nhiệm vụ tăng tương tác. Ban đầu, sinh viên được trả một khoản hoa hồng nhỏ để tạo lòng tin. Sau đó, đối tượng yêu cầu nạp tiền trước để nhận nhiệm vụ có giá trị cao hơn rồi đưa ra nhiều lý do để không cho rút tiền.","Đối tượng mạo danh công ty truyền thông hoặc sàn thương mại điện tử, tiếp cận sinh viên qua Telegram, Zalo hoặc Facebook và mời làm nhiệm vụ tăng tương tác. Ban đầu, sinh viên được",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["tuyen","dung","viec","luong","nhiem","like","share","hoac","pham","tuong","danh","cong","truyen","thong"]),
S("Mạo danh giảng viên hoặc đơn vị của ULIS gửi đường link khảo sát, học bổng hoặc thư trúng tuyển giả","Mạng & giả mạo","⚠️","Sinh viên nhận được email hoặc tin nhắn từ tài khoản có tên và hình ảnh giống giảng viên, khoa hoặc phòng ban của Nhà trường. Nội dung yêu cầu truy cập một đường link lạ để đăng nhập, cập nhật thông tin hoặc xác nhận học bổng. Sau khi sinh viên nhập tài khoản và mật khẩu, đối tượng chiếm quyền sử dụng email hoặc cổng thông tin sinh viên.","Em nhận được email có logo ULIS và tên một phòng ban, bảo em bấm link để xác nhận học bổng. Em có nên đăng nhập không?",["Tên và ảnh đại diện giống giảng viên hoặc đơn vị nhưng không xác minh được nguồn.","Yêu cầu bấm đường link lạ để đăng nhập, cập nhật thông tin hoặc nhận học bổng.","Đường link không thuộc tên miền/kênh chính thức của ULIS.","Tạo cảm giác gấp như phải xác nhận trong ngày.","Yêu cầu mật khẩu, OTP hoặc thông tin đăng nhập.","Sau khi nhập thông tin có dấu hiệu đăng nhập bất thường hoặc mất quyền truy cập."],"Tình huống bạn mô tả có dấu hiệu cần thận trọng vì thông báo sử dụng danh nghĩa của giảng viên hoặc đơn vị Nhà trường và yêu cầu truy cập đường link để đăng nhập. Chỉ dựa vào tên, logo hoặc ảnh đại diện thì chưa thể khẳng định đây là thông báo thật.",["danh","giang","vien","hoac","ulis","uong","link","khao","bong","trung","tuyen","sinh","nhan","email"]),
S("Giả danh công an hoặc Viện kiểm sát, đe dọa sinh viên liên quan đến vụ án","Mạng & giả mạo","⚠️","Đối tượng gọi điện, tự xưng là cán bộ công an hoặc Viện kiểm sát và thông báo tài khoản ngân hàng, căn cước công dân hoặc số điện thoại của sinh viên có liên quan đến ma túy, rửa tiền hoặc hoạt động phi pháp. Sinh viên bị yêu cầu giữ bí mật, tải ứng dụng lạ hoặc chuyển tiền vào tài khoản “tạm giữ” để chứng minh mình vô tội.","Có người gọi nói em liên quan đến vụ án rửa tiền và bảo không được nói với ai. Họ yêu cầu chuyển tiền để chứng minh em vô tội, em phải làm sao?",["Tự xưng công an/Viện kiểm sát và dùng thông tin cá nhân để tạo tin cậy.","Đe dọa liên quan đến ma túy, rửa tiền hoặc vụ án.","Yêu cầu giữ bí mật, cắt liên lạc với người thân.","Yêu cầu chuyển tiền vào tài khoản “tạm giữ”.","Yêu cầu cài ứng dụng hoặc thực hiện thao tác trên điện thoại.","Liên tục thúc giục và tạo cảm giác nếu không làm ngay sẽ bị bắt."],"Cách thức bạn mô tả có nhiều dấu hiệu của thủ đoạn giả danh cơ quan chức năng. Cơ quan chức năng không nên được xác minh chỉ bằng cuộc gọi, giấy tờ gửi qua mạng hoặc yêu cầu chuyển tiền vào tài khoản cá nhân. Bạn nên:",["danh","cong","hoac","vien","kiem","sinh","lien","quan","tuong","xung","thong","khoan","ngan","hang"]),
S("Thông báo nhận quà có giá trị lớn từ nước ngoài","Mạng & giả mạo","⚠️","Một người quen qua mạng tự xưng là chuyên gia, doanh nhân hoặc quân nhân nước ngoài, hứa gửi quà, tiền hoặc tài sản có giá trị về Việt Nam. Sau đó, người khác giả danh hải quan hoặc nhân viên chuyển phát liên hệ, yêu cầu sinh viên đóng phí hải quan, phí thông quan hoặc tiền phạt để nhận quà.","Một người quen qua mạng tự xưng là chuyên gia, doanh nhân hoặc quân nhân nước ngoài, hứa gửi quà, tiền hoặc tài sản có giá trị về Việt Nam. Sau đó, người khác giả danh hải quan hoặ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["thong","nhan","nuoc","ngoai","nguoi","quen","mang","xung","chuyen","doanh","hoac","quan","tien","viet"]),
S("Hack tài khoản Facebook hoặc Zalo của bạn bè để nhắn tin mượn tiền","Mạng & giả mạo","⚠️","Đối tượng chiếm quyền sử dụng tài khoản mạng xã hội của một sinh viên, sau đó dùng cách nói chuyện quen thuộc để nhắn tin cho bạn bè và người thân. Đối tượng viện lý do cấp cứu, tai nạn, đóng học phí hoặc cần thanh toán gấp để yêu cầu chuyển tiền vào một tài khoản khác.","Đối tượng chiếm quyền sử dụng tài khoản mạng xã hội của một sinh viên, sau đó dùng cách nói chuyện quen thuộc để nhắn tin cho bạn bè và người thân. Đối tượng viện lý do cấp cứu, ta",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["hack","khoan","facebook","hoac","zalo","nhan","muon","tien","tuong","chiem","quyen","dung","mang","sinh"]),
S("Lừa đảo bán vé concert, vé máy bay hoặc vé sự kiện trên mạng xã hội","Mạng & giả mạo","⚠️","Đối tượng lập tài khoản hoặc hội nhóm giả, đăng bán vé concert, vé máy bay hoặc vé sự kiện với giá hấp dẫn. Khi sinh viên chuyển khoản đặt cọc hoặc thanh toán toàn bộ, đối tượng chặn liên lạc, gửi vé giả hoặc bán cùng một vé cho nhiều người.","Đối tượng lập tài khoản hoặc hội nhóm giả, đăng bán vé concert, vé máy bay hoặc vé sự kiện với giá hấp dẫn. Khi sinh viên chuyển khoản đặt cọc hoặc thanh toán toàn bộ, đối tượng ch",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["concert","hoac","kien","tren","mang","tuong","khoan","nhom","sinh","vien","chuyen","thanh","toan","chan"]),
S("Tuyển cộng tác viên dịch thuật, nhập liệu hoặc viết nội dung nhưng yêu cầu đóng phí","Mạng & giả mạo","⚠️","Đối tượng nhắm vào sinh viên ngoại ngữ, quảng cáo công việc dịch sách, biên dịch, nhập liệu hoặc viết nội dung với mức thù lao cao. Trước khi nhận việc, sinh viên phải đóng phí bảo hiểm, phí tài khoản, phí bản quyền tài liệu hoặc phí giữ chỗ rồi không nhận được công việc như cam kết.","Em được tuyển cộng tác viên dịch thuật, lương khá cao nhưng họ yêu cầu đóng phí tài khoản trước. Có nên đóng không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Đáng ngờ khi công việc không có thông tin tuyển dụng rõ ràng, thu nhập cao bất thường và yêu cầu đóng phí trước. Nguy cơ cao khi đã chuyển tiền hoặc bị yêu cầu đóng thêm để nhận việc.",["tuyen","cong","vien","dich","thuat","nhap","lieu","hoac","viet","dung","nhung","tuong","nham","sinh"]),
S("Yêu cầu cài đặt ứng dụng dịch vụ công, VNeID hoặc bảo hiểm xã hội giả","Mạng & giả mạo","⚠️","Đối tượng giả danh cán bộ cơ quan nhà nước, yêu cầu sinh viên cài đặt ứng dụng qua file APK hoặc đường link ngoài cửa hàng ứng dụng. Ứng dụng giả có thể chiếm quyền điều khiển điện thoại, đọc tin nhắn, lấy mã OTP hoặc truy cập ứng dụng ngân hàng.","Đối tượng giả danh cán bộ cơ quan nhà nước, yêu cầu sinh viên cài đặt ứng dụng qua file APK hoặc đường link ngoài cửa hàng ứng dụng. Ứng dụng giả có thể chiếm quyền điều khiển điện",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["dung","dich","cong","vneid","hoac","hiem","tuong","danh","quan","nuoc","sinh","vien","file","uong"]),
S("Minigame hoặc chương trình trúng thưởng giả trong hội nhóm sinh viên","Mạng & giả mạo","⚠️","Fanpage hoặc tài khoản giả thông báo sinh viên trúng điện thoại, xe máy, voucher hoặc học bổng. Để nhận giải, sinh viên phải truy cập đường link, cung cấp thông tin tài khoản hoặc đóng phí vận chuyển, phí xác nhận và thuế trước.","Fanpage hoặc tài khoản giả thông báo sinh viên trúng điện thoại, xe máy, voucher hoặc học bổng. Để nhận giải, sinh viên phải truy cập đường link, cung cấp thông tin tài khoản hoặc ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["minigame","hoac","chuong","trinh","trung","thuong","trong","nhom","sinh","vien","fanpage","khoan","thong","thoai"]),
S("Mã độc trong tài liệu học tập hoặc phần mềm bẻ khóa","Mạng & giả mạo","⚠️","Đối tượng chia sẻ tài liệu ôn thi, giáo trình, phần mềm học ngoại ngữ hoặc phần mềm bẻ khóa trong các hội nhóm sinh viên. File tải xuống có thể chứa mã độc đánh cắp mật khẩu, dữ liệu trình duyệt hoặc thông tin tài khoản của người dùng.","Đối tượng chia sẻ tài liệu ôn thi, giáo trình, phần mềm học ngoại ngữ hoặc phần mềm bẻ khóa trong các hội nhóm sinh viên. File tải xuống có thể chứa mã độc đánh cắp mật khẩu, dữ li",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["trong","lieu","hoac","phan","khoa","tuong","chia","giao","trinh","ngoai","nhom","sinh","vien","file"]),
S("Bẫy đầu tư tài chính hoặc “đọc lệnh kiếm tiền” qua ứng dụng giả","Tiền bạc & tài chính","⚠️","Đối tượng khoe ảnh lợi nhuận cao, mời sinh viên tham gia đầu tư tiền mã hóa, giao dịch tài chính hoặc quỹ đầu tư dành cho sinh viên. Ban đầu, người dùng có thể rút một khoản lãi nhỏ. Sau đó, hệ thống yêu cầu nạp thêm tiền để nâng cấp tài khoản, đóng thuế hoặc mở khóa việc rút tiền.","Một nhóm đầu tư cho sinh viên cho em rút được ít lãi lúc đầu, giờ họ bảo nạp thêm để nâng cấp tài khoản. Có nên tiếp tục không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Nguy cơ cao khi có yêu cầu nạp tiền để rút tiền, đóng thuế/mở khóa hoặc thúc giục vay tiền. Số dư hiển thị trên nền tảng không phải bằng chứng tiền thực sự tồn tại.",["chinh","hoac","lenh","kiem","tien","dung","tuong","khoe","nhuan","sinh","vien","tham","giao","dich"]),
S("Vay tiền qua ứng dụng tín dụng đen","Tiền bạc & tài chính","⚠️","Sinh viên cần tiền đóng học phí, thuê trọ hoặc chi tiêu nên tìm đến ứng dụng cho vay nhanh chỉ cần căn cước công dân. Khoản vay có lãi suất và phí cao, đồng thời ứng dụng truy cập danh bạ, hình ảnh và dữ liệu cá nhân để đe dọa người vay và người thân khi chậm thanh toán.","Sinh viên cần tiền đóng học phí, thuê trọ hoặc chi tiêu nên tìm đến ứng dụng cho vay nhanh chỉ cần căn cước công dân. Khoản vay có lãi suất và phí cao, đồng thời ứng dụng truy cập ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["tien","dung","sinh","vien","thue","hoac","tieu","nhanh","cuoc","cong","khoan","suat","thoi","truy"]),
S("Thuê hoặc mua tài khoản ngân hàng của sinh viên","Tiền bạc & tài chính","⚠️","Đối tượng đề nghị sinh viên mở hộ, cho thuê hoặc bán tài khoản ngân hàng để nhận tiền hoa hồng. Tài khoản sau đó có thể bị sử dụng để nhận tiền lừa đảo, đánh bạc hoặc rửa tiền, khiến sinh viên bị phong tỏa tài khoản hoặc phải làm việc với cơ quan chức năng.","Đối tượng đề nghị sinh viên mở hộ, cho thuê hoặc bán tài khoản ngân hàng để nhận tiền hoa hồng. Tài khoản sau đó có thể bị sử dụng để nhận tiền lừa đảo, đánh bạc hoặc rửa tiền, khi",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["thue","hoac","khoan","ngan","hang","sinh","vien","tuong","nghi","nhan","tien","hong","dung","khien"]),
S("Giả danh nhân viên nhà mạng, yêu cầu cung cấp OTP để nâng cấp SIM","Tiền bạc & tài chính","⚠️","Đối tượng gọi điện thông báo nâng cấp SIM 4G, 5G hoặc đăng ký gói cước ưu đãi. Sinh viên được yêu cầu đọc mã OTP hoặc thực hiện cú pháp chuyển đổi SIM, qua đó đối tượng chiếm quyền sử dụng số điện thoại và tiếp tục truy cập các tài khoản khác.","Đối tượng gọi điện thông báo nâng cấp SIM 4G, 5G hoặc đăng ký gói cước ưu đãi. Sinh viên được yêu cầu đọc mã OTP hoặc thực hiện cú pháp chuyển đổi SIM, qua đó đối tượng chiếm quyền",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["danh","nhan","vien","mang","cung","nang","tuong","thong","hoac","cuoc","sinh","thuc","hien","phap"]),
S("Thông báo hoàn thuế hoặc nhận tiền hỗ trợ học tập giả","Tiền bạc & tài chính","⚠️","Sinh viên nhận được thông báo về khoản hoàn thuế, hỗ trợ học tập, trợ cấp hoặc tiền chính sách. Đối tượng yêu cầu cung cấp thông tin ngân hàng, mật khẩu, mã PIN hoặc OTP để nhận tiền.","Sinh viên nhận được thông báo về khoản hoàn thuế, hỗ trợ học tập, trợ cấp hoặc tiền chính sách. Đối tượng yêu cầu cung cấp thông tin ngân hàng, mật khẩu, mã PIN hoặc OTP để nhận ti",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["thong","hoan","thue","hoac","nhan","tien","sinh","vien","khoan","chinh","sach","tuong","cung","ngan"]),
S("Lừa đảo mua bán đồ cũ trong hội nhóm sinh viên","Tiền bạc & tài chính","⚠️","Đối tượng đăng bán bếp từ, tủ lạnh, xe máy, máy tính hoặc đồ dùng sinh viên với giá rẻ. Người mua bị yêu cầu đặt cọc vì “có nhiều người hỏi”, nhưng sau khi chuyển tiền thì bị chặn liên lạc hoặc nhận sản phẩm hỏng, không đúng mô tả.","Đối tượng đăng bán bếp từ, tủ lạnh, xe máy, máy tính hoặc đồ dùng sinh viên với giá rẻ. Người mua bị yêu cầu đặt cọc vì “có nhiều người hỏi”, nhưng sau khi chuyển tiền thì bị chặn ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["trong","nhom","sinh","vien","tuong","lanh","tinh","hoac","dung","nguoi","nhieu","nhung","chuyen","tien"]),
S("Thông báo trúng học bổng hoặc chương trình trao đổi nhưng yêu cầu đóng tiền cọc","Tiền bạc & tài chính","⚠️","Sinh viên nhận được thư thông báo trúng tuyển chương trình trao đổi hoặc học bổng quốc tế có sử dụng tên, logo và con dấu giống Nhà trường. Thư yêu cầu đóng phí cam kết, phí vé máy bay hoặc phí hồ sơ vào tài khoản cá nhân trong thời gian ngắn.","Sinh viên nhận được thư thông báo trúng tuyển chương trình trao đổi hoặc học bổng quốc tế có sử dụng tên, logo và con dấu giống Nhà trường. Thư yêu cầu đóng phí cam kết, phí vé máy",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["thong","trung","bong","hoac","chuong","trinh","trao","nhung","tien","sinh","vien","nhan","tuyen","quoc"]),
S("Kinh doanh đa cấp núp bóng khởi nghiệp sinh viên","Tiền bạc & tài chính","⚠️","Sinh viên được mời tham gia hội thảo phát triển bản thân, khởi nghiệp hoặc làm giàu. Sau đó, người tham gia bị yêu cầu mua gói sản phẩm có giá trị lớn, vay tiền để tham gia hoặc tuyển thêm người mới để nhận hoa hồng.","Sinh viên được mời tham gia hội thảo phát triển bản thân, khởi nghiệp hoặc làm giàu. Sau đó, người tham gia bị yêu cầu mua gói sản phẩm có giá trị lớn, vay tiền để tham gia hoặc tu",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["kinh","doanh","bong","khoi","nghiep","sinh","vien","tham","thao","phat","trien","than","hoac","giau"]),
S("Việc làm tại nhà yêu cầu đóng phí nguyên liệu hoặc phí giữ ca","Tiền bạc & tài chính","⚠️","Đối tượng quảng cáo việc đóng gói hàng, gấp giấy, xâu chuỗi hoặc dán nhãn sản phẩm tại nhà với thu nhập cao. Sinh viên phải đóng phí nhận nguyên liệu, phí hồ sơ hoặc phí giữ ca nhưng không nhận được việc làm.","Đối tượng quảng cáo việc đóng gói hàng, gấp giấy, xâu chuỗi hoặc dán nhãn sản phẩm tại nhà với thu nhập cao. Sinh viên phải đóng phí nhận nguyên liệu, phí hồ sơ hoặc phí giữ ca như",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["viec","nguyen","lieu","hoac","tuong","quang","hang","giay","chuoi","nhan","pham","nhap","sinh","vien"]),
S("Bảo hiểm xe máy hoặc bảo hiểm y tế giả","Tiền bạc & tài chính","⚠️","Tài khoản mạng xã hội rao bán bảo hiểm xe máy hoặc bảo hiểm y tế với mức giá thấp bất thường. Sinh viên nhận được giấy chứng nhận hoặc mã bảo hiểm giả, không có giá trị khi kiểm tra hoặc khi xảy ra sự cố.","Tài khoản mạng xã hội rao bán bảo hiểm xe máy hoặc bảo hiểm y tế với mức giá thấp bất thường. Sinh viên nhận được giấy chứng nhận hoặc mã bảo hiểm giả, không có giá trị khi kiểm tr",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["hiem","hoac","khoan","mang","thap","thuong","sinh","vien","nhan","giay","chung","khong","kiem"]),
S("Romance Scam xuyên quốc gia qua ứng dụng hẹn hò","Tình cảm & thao túng","🛡️","Đối tượng giả làm doanh nhân, chuyên gia tài chính hoặc quân nhân nước ngoài, trò chuyện trong thời gian dài để xây dựng quan hệ tình cảm. Sau đó, người này viện lý do gặp tai nạn, khó khăn tài chính hoặc rủ sinh viên đầu tư chung vào một nền tảng giả.","Đối tượng giả làm doanh nhân, chuyên gia tài chính hoặc quân nhân nước ngoài, trò chuyện trong thời gian dài để xây dựng quan hệ tình cảm. Sau đó, người này viện lý do gặp tai nạn,",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["romance","scam","xuyen","quoc","dung","tuong","doanh","nhan","chuyen","chinh","hoac","quan","nuoc","ngoai"]),
S("“Sugar daddy” hoặc “sugar baby” giả yêu cầu đóng phí trước","Tình cảm & thao túng","🛡️","Đối tượng hứa chu cấp một khoản tiền lớn nhưng yêu cầu sinh viên đóng phí kích hoạt tài khoản, phí làm hợp đồng bảo mật hoặc mua quà trước khi nhận tiền. Sau khi nhận được tiền, đối tượng cắt liên lạc.","Đối tượng hứa chu cấp một khoản tiền lớn nhưng yêu cầu sinh viên đóng phí kích hoạt tài khoản, phí làm hợp đồng bảo mật hoặc mua quà trước khi nhận tiền. Sau khi nhận được tiền, đố",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["sugar","daddy","hoac","baby","truoc","tuong","khoan","tien","nhung","sinh","vien","kich","hoat","nhan"]),
S("Lừa tình kết hợp tống tiền bằng hình ảnh nhạy cảm","Tình cảm & thao túng","🛡️","Đối tượng làm quen, tán tỉnh và dụ sinh viên gửi ảnh riêng tư hoặc tham gia cuộc gọi video nhạy cảm. Đối tượng bí mật ghi lại nội dung, sau đó đe dọa gửi cho gia đình, bạn bè hoặc Nhà trường để ép nạn nhân chuyển tiền.","Người em quen qua mạng đang giữ ảnh riêng tư và dọa gửi cho bạn bè nếu em không chuyển tiền. Em phải làm gì?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Không chuyển tiền hoặc gửi thêm nội dung để đáp ứng yêu cầu tống tiền. Cần lưu bằng chứng, tăng bảo mật tài khoản và chuyển hỗ trợ con người khi có đe dọa phát tán.",["tinh","tong","tien","bang","hinh","nhay","tuong","quen","sinh","vien","rieng","hoac","tham","cuoc"]),
S("Hứa kết hôn hoặc đưa đi du học, định cư để vay tiền","Tình cảm & thao túng","🛡️","Đối tượng xây dựng quan hệ tình cảm, hứa kết hôn hoặc giúp sinh viên ra nước ngoài. Sau đó, người này liên tục tạo ra các biến cố như bệnh tật, mất giấy tờ hoặc khó khăn tài chính để yêu cầu sinh viên chuyển tiền.","Người yêu online nói sẽ đưa em đi du học nhưng đang thiếu tiền làm giấy tờ và muốn em chuyển trước. Em có nên tin không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Cần xác minh độc lập danh tính, câu chuyện và giấy tờ. Nguy cơ cao khi có yêu cầu chuyển tiền lặp lại, lý do khẩn cấp hoặc không thể kiểm chứng.",["hoac","tien","tuong","dung","quan","tinh","giup","sinh","vien","nuoc","ngoai","nguoi","lien","bien"]),
S("Lợi dụng tình cảm bạn bè để vay tiền rồi cắt liên lạc","Tình cảm & thao túng","🛡️","Một người mới quen trong lớp, câu lạc bộ hoặc nơi làm thêm tỏ ra quan tâm và thường xuyên giúp đỡ sinh viên. Sau khi tạo được lòng tin, người này vay một khoản tiền lớn với lý do gia đình có việc khẩn cấp rồi biến mất.","Một người mới quen trong lớp, câu lạc bộ hoặc nơi làm thêm tỏ ra quan tâm và thường xuyên giúp đỡ sinh viên. Sau khi tạo được lòng tin, người này vay một khoản tiền lớn với lý do g",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["dung","tinh","tien","lien","nguoi","quen","trong","hoac","them","quan","thuong","xuyen","giup","sinh"]),
S("Dụ người yêu tham gia hội nhóm hoặc tổ chức có dấu hiệu kiểm soát","Tình cảm & thao túng","🛡️","Sinh viên được người yêu hoặc người thân thiết rủ tham gia các buổi giao lưu kỹ năng sống, hội nhóm tâm linh hoặc câu lạc bộ phát triển bản thân. Sau đó, người tham gia bị yêu cầu đóng tiền, tuyển thêm thành viên và hạn chế liên lạc với gia đình, bạn bè.","Sinh viên được người yêu hoặc người thân thiết rủ tham gia các buổi giao lưu kỹ năng sống, hội nhóm tâm linh hoặc câu lạc bộ phát triển bản thân. Sau đó, người tham gia bị yêu cầu ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["nguoi","tham","nhom","hoac","chuc","hieu","kiem","soat","sinh","vien","than","thiet","buoi","giao"]),
S("Rủ đi du lịch chung rồi chiếm đoạt tiền đặt cọc","Tình cảm & thao túng","🛡️","Đối tượng xây dựng quan hệ tình cảm, đề xuất tổ chức chuyến du lịch cho hai người và nhận tiền đặt vé, phòng khách sạn hoặc dịch vụ. Trước ngày khởi hành, đối tượng cắt liên lạc và giữ toàn bộ số tiền.","Người yêu rủ em đi du lịch và bảo em chuyển tiền đặt phòng cho cả hai. Em có nên chuyển không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Không chuyển tiền chỉ dựa trên lời hứa hoặc áp lực thời gian. Xác minh đặt phòng/vé trực tiếp với nhà cung cấp và danh tính người nhận.",["lich","chung","chiem","tien","tuong","dung","quan","tinh","xuat","chuc","chuyen","nguoi","nhan","phong"]),
S("Giả mạo người thân hoặc bạn của người yêu để báo tin cấp cứu","Tình cảm & thao túng","🛡️","Đối tượng thu thập thông tin cá nhân từ mạng xã hội rồi gọi điện, tự xưng là bạn hoặc người thân của người yêu. Đối tượng thông báo người yêu đang cấp cứu hoặc gặp tai nạn và yêu cầu sinh viên chuyển tiền viện phí ngay.","Có người gọi nói bạn trai em bị tai nạn và cần chuyển tiền viện phí ngay. Em chưa liên lạc được với bạn trai.",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Tin khẩn cấp cần được xác minh bằng một kênh độc lập. Tài khoản cá nhân, yêu cầu chuyển gấp và không cho người dùng tự xác minh là dấu hiệu đáng ngờ.",["nguoi","than","hoac","tuong","thap","thong","nhan","mang","xung","sinh","vien","chuyen","tien","ngay"]),
S("Lừa đảo qua dịch vụ gỡ rối tình cảm, bùa yêu hoặc giải hạn","Tình cảm & thao túng","🛡️","Khi sinh viên gặp khó khăn trong chuyện tình cảm, tài khoản xem bói hoặc dịch vụ tâm linh tiếp cận và hứa giúp người yêu quay lại. Sinh viên liên tục bị yêu cầu đóng thêm phí để thực hiện các nghi lễ hoặc hóa giải những “vấn đề mới”.","Khi sinh viên gặp khó khăn trong chuyện tình cảm, tài khoản xem bói hoặc dịch vụ tâm linh tiếp cận và hứa giúp người yêu quay lại. Sinh viên liên tục bị yêu cầu đóng thêm phí để th",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["dich","tinh","hoac","giai","sinh","vien","khan","trong","chuyen","khoan","linh","tiep","giup","nguoi"]),
S("Mạo danh người giàu có tuyển trợ lý riêng kèm điều kiện tình cảm","Tình cảm & thao túng","🛡️","Đối tượng đăng tuyển thư ký hoặc trợ lý riêng với mức lương cao, yêu cầu ngoại hình và sẵn sàng đi công tác riêng. Sinh viên có thể bị yêu cầu đóng phí khám sức khỏe, phí đồng phục, gửi ảnh riêng tư hoặc đến phỏng vấn tại địa điểm không phù hợp.","Đối tượng đăng tuyển thư ký hoặc trợ lý riêng với mức lương cao, yêu cầu ngoại hình và sẵn sàng đi công tác riêng. Sinh viên có thể bị yêu cầu đóng phí khám sức khỏe, phí đồng phục",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["danh","nguoi","giau","tuyen","rieng","kien","tinh","tuong","hoac","luong","ngoai","hinh","sang","cong"]),
S("Trung tâm gia sư thu phí nhận lớp nhưng không giao lớp","Gia sư, nhà trọ & việc làm","🏠","Trung tâm đăng thông tin tuyển gia sư cho một lớp có mức lương hấp dẫn. Sinh viên được yêu cầu chuyển phí nhận lớp hoặc tiền đặt cọc. Sau khi nhận tiền, trung tâm trì hoãn, cung cấp địa chỉ sai, thông báo phụ huynh hủy lớp hoặc chặn liên lạc.","Trung tâm gia sư bảo em chuyển phí nhận lớp trước rồi mới cho số phụ huynh. Em có nên chuyển không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Yêu cầu phí trước cần được kiểm tra bằng hợp đồng, thông tin trung tâm và điều khoản hoàn phí. Nguy cơ cao khi đã thu tiền nhưng không giao lớp hoặc liên tục yêu cầu đóng thêm.",["trung","nhan","nhung","khong","giao","thong","tuyen","luong","sinh","vien","chuyen","hoac","tien","hoan"]),
S("Yêu cầu gia sư dạy thử dài ngày nhưng không trả tiền công","Gia sư, nhà trọ & việc làm","🏠","Đơn vị trung gian giới thiệu sinh viên đến dạy gia sư và thông báo rằng phụ huynh chỉ thanh toán sau thời gian thử việc. Sau nhiều tuần hoặc một tháng, phụ huynh cho biết họ đã trả tiền cho trung tâm hoặc được thông báo đây là giai đoạn dạy thử miễn phí, khiến sinh viên không nhận được tiền công.","Đơn vị trung gian giới thiệu sinh viên đến dạy gia sư và thông báo rằng phụ huynh chỉ thanh toán sau thời gian thử việc. Sau nhiều tuần hoặc một tháng, phụ huynh cho biết họ đã trả",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["ngay","nhung","khong","tien","cong","trung","gian","gioi","thieu","sinh","vien","thong","rang","huynh"]),
S("Phòng trọ giá rẻ yêu cầu chuyển tiền cọc trước khi xem phòng","Gia sư, nhà trọ & việc làm","🏠","Đối tượng đăng phòng trọ có vị trí thuận lợi và mức giá thấp. Khi sinh viên hỏi thuê, người đăng nói đang ở xa hoặc có nhiều người quan tâm nên yêu cầu chuyển tiền giữ phòng trước khi xem trực tiếp. Sau khi nhận cọc, đối tượng chặn liên lạc hoặc địa chỉ phòng không tồn tại.","Chủ trọ nói phòng rất rẻ nhưng em phải chuyển 1 triệu giữ phòng trước khi được xem. Có nên cọc không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Không chuyển cọc trước khi xác minh phòng và quyền cho thuê. Nguy cơ cao khi người đăng né gặp trực tiếp, thúc giục và nhận tiền vào tài khoản không xác minh được.",["phong","chuyen","tien","truoc","tuong","thuan","thap","sinh","vien","thue","nguoi","hoac","nhieu","quan"]),
S("Giả danh chủ nhà, sử dụng giấy tờ và hợp đồng giả","Gia sư, nhà trọ & việc làm","🏠","Đối tượng cho sinh viên xem một căn phòng nhưng không phải chủ sở hữu, sau đó gửi căn cước công dân, giấy tờ nhà và hợp đồng có dấu hiệu chỉnh sửa. Sinh viên được yêu cầu chuyển tiền cọc vào tài khoản không trùng tên người cho thuê hoặc ký hợp đồng mà chưa xác minh quyền cho thuê.","Đối tượng cho sinh viên xem một căn phòng nhưng không phải chủ sở hữu, sau đó gửi căn cước công dân, giấy tờ nhà và hợp đồng có dấu hiệu chỉnh sửa. Sinh viên được yêu cầu chuyển ti",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["danh","dung","giay","tuong","sinh","vien","phong","nhung","khong","phai","cuoc","cong","hieu","chinh"]),
S("Giả danh shipper giao đơn hàng của khoa rồi chuyển sang video call giả công an","Gia sư, nhà trọ & việc làm","🏠","Sinh viên nhận cuộc gọi từ người tự xưng là shipper, thông báo có tài liệu hoặc đơn hàng do khoa gửi nhưng không giao được. Sau khi kết bạn qua Zalo và gọi video, sinh viên nhìn thấy người mặc trang phục công an và bị thông báo có liên quan đến ma túy hoặc rửa tiền.","Sinh viên nhận cuộc gọi từ người tự xưng là shipper, thông báo có tài liệu hoặc đơn hàng do khoa gửi nhưng không giao được. Sau khi kết bạn qua Zalo và gọi video, sinh viên nhìn th",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["danh","shipper","giao","hang","khoa","chuyen","sang","video","call","cong","sinh","vien","nhan","cuoc"]),
S("Giả công an yêu cầu sinh viên thuê khách sạn, ở một mình và giữ bí mật","Gia sư, nhà trọ & việc làm","🏠","Sau khi tạo tâm lý sợ hãi, đối tượng yêu cầu sinh viên không được báo cho gia đình hoặc Nhà trường, phải di chuyển đến khách sạn, ở một mình và mở video call liên tục để “phục vụ điều tra”. Đối tượng tiếp tục hướng dẫn sinh viên xin tiền gia đình bằng lý do giả như đóng học bổng hoặc phí trao đổi.","Sau khi tạo tâm lý sợ hãi, đối tượng yêu cầu sinh viên không được báo cho gia đình hoặc Nhà trường, phải di chuyển đến khách sạn, ở một mình và mở video call liên tục để “phục vụ đ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["cong","sinh","vien","thue","khach","minh","tuong","khong","hoac","truong","phai","chuyen","video","call"]),
S("Chương trình thực tập hoặc làm việc ở nước ngoài giả","Gia sư, nhà trọ & việc làm","🏠","Sinh viên nhận được thư mời thực tập tại doanh nghiệp quốc tế hoặc chương trình trải nghiệm ở nước ngoài với mức hỗ trợ cao. Đơn vị tuyển dụng yêu cầu đóng phí hồ sơ, phí đào tạo, phí visa hoặc mua vé qua một tài khoản cá nhân trước khi cung cấp hợp đồng chính thức.","Sinh viên nhận được thư mời thực tập tại doanh nghiệp quốc tế hoặc chương trình trải nghiệm ở nước ngoài với mức hỗ trợ cao. Đơn vị tuyển dụng yêu cầu đóng phí hồ sơ, phí đào tạo, ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["chuong","trinh","thuc","hoac","viec","nuoc","ngoai","sinh","vien","nhan","doanh","nghiep","quoc","trai"]),
S("Dịch vụ hỗ trợ lấy lại tiền sau khi bị lừa","Gia sư, nhà trọ & việc làm","🏠","Sau khi đăng bài hoặc tìm kiếm cách lấy lại tiền, nạn nhân được một tài khoản tự xưng là luật sư, công an, chuyên gia an ninh mạng hoặc dịch vụ thu hồi tiền tiếp cận. Đối tượng cam kết lấy lại toàn bộ số tiền nhưng yêu cầu đóng phí hồ sơ, phí truy vết hoặc phí mở khóa giao dịch trước.","Em vừa bị lừa tiền, có người nhắn bảo họ có thể lấy lại 100% nếu em đóng phí truy vết. Có nên tin không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Đây là dấu hiệu của nguy cơ bị lừa lần hai. Không chuyển thêm tiền cho người tự tiếp cận và hứa thu hồi tiền nếu phải đóng phí trước; ưu tiên ngân hàng và cơ quan chức năng.",["dich","tien","hoac","kiem","cach","nhan","khoan","xung","luat","cong","chuyen","ninh","mang","tiep"]),
S("Người quen qua mạng rủ gặp tại địa điểm vắng hoặc yêu cầu lên xe riêng","An toàn cá nhân","🚨","Người mới quen qua mạng chủ động hẹn gặp nhưng liên tục thay đổi địa điểm, yêu cầu sinh viên đến nơi vắng, lên xe riêng hoặc không báo cho bạn bè. Khi sinh viên đề nghị gặp ở nơi công cộng hoặc đi cùng bạn, người này gây áp lực, giận dữ hoặc đe dọa chấm dứt quan hệ.","Người mới quen qua mạng chủ động hẹn gặp nhưng liên tục thay đổi địa điểm, yêu cầu sinh viên đến nơi vắng, lên xe riêng hoặc không báo cho bạn bè. Khi sinh viên đề nghị gặp ở nơi c",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["nguoi","quen","mang","vang","hoac","rieng","nhung","lien","thay","sinh","vien","khong","nghi","cong"]),
S("Tuyển người mẫu, diễn viên hoặc PG nhưng yêu cầu phỏng vấn tại khách sạn, nhà riêng","An toàn cá nhân","🚨","Đối tượng đăng tuyển người mẫu ảnh, diễn viên, PG hoặc nhân viên sự kiện với mức thù lao cao. Ứng viên được yêu cầu gửi ảnh nhạy cảm, thử trang phục riêng hoặc đến khách sạn, căn hộ và nhà riêng để phỏng vấn mà không có thông tin doanh nghiệp rõ ràng.","Em được tuyển PG lương cao nhưng họ hẹn phỏng vấn ở khách sạn và bảo đi một mình. Có nên đi không?",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Không đến địa điểm riêng hoặc vắng một mình và không gửi ảnh riêng tư để đổi lấy cơ hội việc làm. Ưu tiên xác minh doanh nghiệp, địa điểm và người phụ trách.",["tuyen","nguoi","dien","vien","hoac","nhung","phong","khach","rieng","tuong","nhan","kien","nhay","trang"]),
S("Người yêu kiểm soát vị trí và cô lập sinh viên khỏi bạn bè, gia đình","An toàn cá nhân","🚨","Người yêu yêu cầu sinh viên bật định vị liên tục, cung cấp mật khẩu điện thoại, báo cáo lịch trình và ngừng gặp một số bạn bè. Khi sinh viên không làm theo, người này đe dọa chia tay, tự làm hại bản thân, tiết lộ bí mật hoặc gây tổn hại đến sinh viên.","Người yêu yêu cầu sinh viên bật định vị liên tục, cung cấp mật khẩu điện thoại, báo cáo lịch trình và ngừng gặp một số bạn bè. Khi sinh viên không làm theo, người này đe dọa chia t",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["nguoi","kiem","soat","sinh","vien","khoi","lien","cung","khau","thoai","lich","trinh","ngung","khong"]),
S("Ép gửi ảnh riêng tư hoặc thực hiện hành vi không mong muốn","An toàn cá nhân","🚨","Người yêu hoặc người đang tìm hiểu dùng lời hứa, sự giận dỗi, đe dọa chia tay hoặc những món quà đã tặng để gây áp lực, buộc sinh viên gửi hình ảnh riêng tư, gọi video nhạy cảm hoặc thực hiện hành vi mà sinh viên không thực sự đồng ý.","Người yêu giận và bảo nếu em không gửi ảnh riêng tư thì sẽ chia tay. Em không muốn gửi nhưng rất áp lực.",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Việc đã yêu nhau, nhận quà hoặc từng đồng ý trước đó không làm mất quyền từ chối hiện tại. Không gửi thêm nội dung để đáp ứng áp lực; tìm người đáng tin cậy hỗ trợ nếu bị đe dọa.",["rieng","hoac","thuc","hien","hanh","khong","mong","muon","nguoi","hieu","dung","gian","chia","nhung"]),
S("Tống tiền bằng hình ảnh giả tạo bởi AI hoặc hình ảnh lấy từ tài khoản bị hack","An toàn cá nhân","🚨","Đối tượng sử dụng ảnh công khai của sinh viên để tạo hình ảnh nhạy cảm giả bằng AI, hoặc lấy hình ảnh từ tài khoản bị chiếm quyền. Sau đó, đối tượng đe dọa phát tán nội dung và yêu cầu chuyển tiền, gửi thêm ảnh hoặc thực hiện các yêu cầu khác.","Đối tượng sử dụng ảnh công khai của sinh viên để tạo hình ảnh nhạy cảm giả bằng AI, hoặc lấy hình ảnh từ tài khoản bị chiếm quyền. Sau đó, đối tượng đe dọa phát tán nội dung và yêu",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["tong","tien","bang","hinh","hoac","khoan","hack","tuong","dung","cong","khai","sinh","vien","nhay"]),
S("Dụ tham gia tiệc hoặc buổi gặp rồi lợi dụng khi người dùng mất khả năng kiểm soát","An toàn cá nhân","🚨","Sinh viên được mời đến buổi tiệc, sự kiện tuyển dụng hoặc gặp mặt riêng. Tại đó, người mời liên tục ép uống đồ uống không rõ nguồn gốc, ngăn sinh viên liên hệ bạn bè hoặc tìm cách đưa sinh viên đến một địa điểm khác khi họ không còn tỉnh táo.","Sinh viên được mời đến buổi tiệc, sự kiện tuyển dụng hoặc gặp mặt riêng. Tại đó, người mời liên tục ép uống đồ uống không rõ nguồn gốc, ngăn sinh viên liên hệ bạn bè hoặc tìm cách ",["Yêu cầu khó xác minh độc lập","Thúc giục hoặc gây áp lực","Yêu cầu tiền, dữ liệu hoặc hành vi rủi ro"],"Dừng lại và xác minh độc lập trước khi tiếp tục. Không chuyển tiền, cung cấp OTP, mật khẩu hoặc giấy tờ nhạy cảm khi chưa kiểm chứng được danh tính và mục đích.",["tham","tiec","hoac","buoi","dung","nguoi","nang","kiem","soat","sinh","vien","kien","tuyen","rieng"]),
S("Lời mời việc làm hoặc du lịch dẫn đến giữ giấy tờ và hạn chế liên lạc","An toàn cá nhân","🚨","Sinh viên được mời đi làm hoặc tham gia chuyến du lịch với chi phí thấp, nhưng khi đến nơi thì bị yêu cầu giao căn cước công dân, hộ chiếu hoặc điện thoại. Người tổ chức thay đổi công việc đã thỏa thuận, hạn chế việc ra ngoài và ngăn sinh viên liên lạc với gia đình.","Em đi làm theo lời giới thiệu, đến nơi họ giữ căn cước và điện thoại của em, bảo đây là quy định.",["Thông tin hoặc lời hứa hấp dẫn nhưng khó kiểm chứng độc lập.","Đối tượng chủ yếu liên hệ qua tài khoản cá nhân hoặc kênh không chính thức.","Yêu cầu chuyển tiền, đóng phí hoặc cung cấp thông tin trước khi quyền lợi được xác minh.","Tạo áp lực thời gian hoặc dùng lý do khẩn cấp để người dùng quyết định nhanh.","Yêu cầu người dùng không nói với người khác hoặc hạn chế việc xác minh.","Thông tin người nhận tiền/tổ chức/địa điểm không trùng khớp hoặc không rõ ràng."],"Đây là nguy cơ an toàn cá nhân cao. Không giao thêm giấy tờ hoặc thiết bị, cố gắng liên hệ người đáng tin cậy và tìm hỗ trợ trực tiếp; ưu tiên rời khỏi nơi nguy hiểm khi có thể làm vậy an toàn.",["viec","hoac","lich","giay","lien","sinh","vien","tham","chuyen","thap","nhung","giao","cuoc","cong"])
];
const groups=["Tất cả","Mạng & giả mạo","Tiền bạc & tài chính","Tình cảm & thao túng","Gia sư, nhà trọ & việc làm","An toàn cá nhân"];
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function analyze(input:string){const t=norm(input);const ranked=scams.map(s=>({s,n:s.keys.filter(k=>t.includes(norm(k))).length})).sort((a,b)=>b.n-a.n);const hit=ranked[0].n>=1?ranked[0].s:null;const danger=/da chuyen|da nap|mat tien|bi de doa|tong tien|giu ho chieu|giu can cuoc|khong cho ra ngoai|khach san|co lap/.test(t);const exposed=/da nhap|da cung cap|da gui|otp|mat khau|cccd|ho chieu|anh rieng tu|video nhay cam/.test(t);const money=/chuyen tien|nap tien|dong phi|dat coc|thanh toan|vay tien|mo khoa/.test(t);if(danger)return `MỨC ĐỘ: NGUY CƠ CAO\n\n${hit?`Tình huống gần nhất: ${hit.title}.\n${hit.action}\n\n`:""}Làm ngay:\n1. Dừng chuyển tiền, gửi dữ liệu hoặc làm theo yêu cầu.\n2. Báo một người đáng tin cậy; không tự xử lý một mình.\n3. Nếu đã chuyển tiền, gọi ngân hàng qua số chính thức.\n4. Lưu tin nhắn, đường link, tài khoản và biên lai.\n5. Nếu đang mất an toàn, đến nơi công cộng hoặc nơi có người hỗ trợ khi có thể an toàn.\n\nKhông chuyển thêm tiền cho người hứa lấy lại tiền.`;if(exposed||money)return `MỨC ĐỘ: ĐÁNG NGỜ / CẦN XỬ LÝ SỚM\n\n${hit?`Có thể liên quan: ${hit.title}.\n${hit.action}\n\n`:""}Dừng lại, không gửi thêm tiền hoặc dữ liệu; xác minh qua kênh chính thức không do đối tượng cung cấp.\n\nBạn đã thực hiện yêu cầu nào chưa, và hiện họ có đang thúc giục hoặc đe dọa bạn không?`;if(hit)return `MỨC ĐỘ: CẦN XÁC MINH THÊM\n\nTình huống có nét giống: ${hit.title}. Chưa thể kết luận chỉ từ thông tin hiện có.\n${hit.desc}\n\nCần biết thêm:\n1. Họ yêu cầu bạn chuyển tiền, đóng phí hoặc cung cấp thông tin gì?\n2. Bạn đã làm theo bước nào chưa?\n3. Họ có đang thúc giục, đe dọa hoặc yêu cầu giữ bí mật không?\n\nKhông gửi OTP, mật khẩu, PIN, CVV hoặc ảnh giấy tờ đầy đủ.`;return "MỨC ĐỘ: CHƯA ĐỦ DỮ KIỆN\n\nHãy mô tả người đó yêu cầu bạn làm gì, có liên quan đến tiền, đường link, ứng dụng, giấy tờ, hình ảnh riêng tư hoặc địa điểm vắng không; đồng thời cho biết bạn đã làm theo bước nào chưa.\n\nKhông gửi OTP, mật khẩu, PIN, CVV hoặc ảnh giấy tờ đầy đủ."}

function rankedMatches(input:string){
  const t=norm(input);
  return scams.map(s=>({s,n:s.keys.filter(k=>t.includes(norm(k))).length})).sort((a,b)=>b.n-a.n);
}

function contextFor(input:string){
  const ranked=rankedMatches(input);
  const hit=ranked[0]?.n>=1?ranked[0].s:null;
  return hit?caseContext(hit):null;
}

function caseContext(hit:Scam){
  return {title:hit.title,group:hit.group,description:hit.desc,signs:hit.signs,action:hit.action};
}

function strongLocalCase(input:string){
  const ranked=rankedMatches(input);
  const best=ranked[0]?.n??0;
  const second=ranked[1]?.n??0;
  return norm(input).length>=24&&best>=3&&best-second>=2?ranked[0].s:null;
}

const ignoredWords=new Set(["anh","ban","bi","biet","cai","cho","co","cua","dang","day","duoc","em","gio","ho","khong","la","lai","lam","minh","mot","nay","nen","nguoi","nhung","phai","roi","sau","thi","the","them","toi","va","voi"]);
function meaningfulWords(input:string){
  return [...new Set(norm(input).replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(w=>w.length>=3&&!ignoredWords.has(w)))];
}

function caseCoversFollowup(hit:Scam,input:string){
  const t=norm(input);
  if(/lam gi|xu ly|nen lam|phai lam|gio sao|tiep theo/.test(t))return true;
  const words=meaningfulWords(input);
  if(words.length===0)return false;
  const corpus=norm([hit.title,hit.desc,hit.example,...hit.signs,hit.action].join(" "));
  const covered=words.filter(w=>corpus.includes(w)).length;
  return covered>=2&&covered/words.length>=0.6;
}

function answerFromCase(hit:Scam,input:string){
  const t=norm(input);
  const urgent=/da chuyen|da nap|mat tien|bi de doa|tong tien|giu ho chieu|giu can cuoc|khong cho ra ngoai|co lap/.test(t);
  if(urgent)return `MỨC ĐỘ: NGUY CƠ CAO\n\nTình huống đang trao đổi: ${hit.title}.\n${hit.action}\n\nLàm ngay:\n1. Dừng chuyển tiền, gửi dữ liệu hoặc làm theo yêu cầu.\n2. Nếu đã chuyển tiền, gọi ngân hàng qua số chính thức để yêu cầu hỗ trợ.\n3. Lưu tin nhắn, đường link, tài khoản nhận tiền và biên lai.\n4. Báo một người đáng tin cậy; nếu có nguy cơ an toàn cá nhân, tìm hỗ trợ trực tiếp.\n\nKhông chuyển thêm tiền cho người hứa lấy lại tiền.`;
  return `MỨC ĐỘ: CẦN THẬN TRỌNG\n\nTình huống đang trao đổi: ${hit.title}.\n\n${hit.action}\n\nDấu hiệu cần đối chiếu:\n${hit.signs.slice(0,4).map((s,i)=>`${i+1}. ${s}`).join("\n")}\n\nNếu xuất hiện chi tiết mới không nằm trong các dấu hiệu trên, hãy nói rõ để trợ lý phân tích thêm.`;
}

function createId(prefix:string){
  const random=typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36);
  return `${prefix}_${random}`;
}

function getUserId(){
  try{
    const key="safestudent_user_id";
    const saved=localStorage.getItem(key);
    if(saved)return saved;
    const created=createId("USER");
    localStorage.setItem(key,created);
    return created;
  }catch{return createId("USER")}
}

function recordLog(payload:{user:string;sessionId:string;input:string;answer:string;responseTimeMs:number;source:string;caseTitle?:string;model?:string;status?:string}){
  fetch("/api/log",{
    method:"POST",
    headers:{"Content-Type":"application/json"},
    body:JSON.stringify(payload),
    keepalive:true
  }).catch(()=>{});
}

type QuizItem={tag:string;question:string;answers:string[];correct:number;explain:string};
const quizData:QuizItem[]=[
  {tag:"HỌC BỔNG",question:"Email học bổng yêu cầu phí gấp vào tài khoản cá nhân. Bạn làm gì trước?",answers:["Chuyển trước để giữ suất","Hỏi người gửi có hoàn tiền không","Tự mở website ULIS và gọi đơn vị chính thức"],correct:2,explain:"Đáp án C. Logo và con dấu không thay thế việc xác minh qua kênh chính thức."},
  {tag:"GIẢ DANH",question:"Người tự xưng công an gọi video, yêu cầu giữ bí mật và chuyển tiền. Bạn làm gì?",answers:["Làm theo vì họ biết thông tin cá nhân","Kết thúc cuộc gọi và tự xác minh","Chuyển một khoản nhỏ để kiểm tra"],correct:1,explain:"Đáp án B. Cơ quan công an không yêu cầu chuyển tiền để chứng minh vô tội qua điện thoại."},
  {tag:"VIỆC LÀM",question:"Trung tâm gia sư thu phí nhưng không cho gặp phụ huynh trước. Lựa chọn an toàn là gì?",answers:["Đóng phí để giữ lớp","Dừng và kiểm chứng trung tâm, phụ huynh, hợp đồng","Gửi ảnh CCCD thay cho phí"],correct:1,explain:"Đáp án B. Cần xác minh người thuê, mức trả, khoản phí và điều kiện hoàn phí bằng văn bản."},
  {tag:"NHÀ TRỌ",question:"Người đăng phòng yêu cầu đặt cọc trước khi cho xem phòng. Bạn nên làm gì?",answers:["Chuyển một nửa tiền cọc","Tin ảnh giấy tờ họ gửi","Xem phòng và xác minh quyền cho thuê"],correct:2,explain:"Đáp án C. Ảnh CCCD hoặc hợp đồng có thể bị đánh cắp, chỉnh sửa hoặc dùng lại."},
  {tag:"TÀI KHOẢN",question:"Bạn đã nhập mật khẩu vào một trang đáng ngờ. Hành động đúng là gì?",answers:["Chờ xem có vấn đề không","Tự mở kênh chính thức, đổi mật khẩu và đăng xuất phiên lạ","Nhắn người gửi yêu cầu xóa dữ liệu"],correct:1,explain:"Đáp án B. Hãy dùng thiết bị an toàn, đổi mật khẩu và bật xác thực nhiều lớp."},
  {tag:"TÀI CHÍNH",question:"Ứng dụng nhiệm vụ yêu cầu nộp thêm phí để được rút tiền. Bạn làm gì?",answers:["Nạp lần cuối để lấy lại tiền","Vay bạn bè hoàn thành nhiệm vụ","Dừng nạp, lưu bằng chứng và gọi ngân hàng"],correct:2,explain:"Đáp án C. Không chuyển thêm tiền để cố lấy lại số tiền đã mất."}
];

export default function Home(){const[group,setGroup]=useState("Tất cả"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Scam|null>(null),[chat,setChat]=useState(false),[input,setInput]=useState(""),[checks,setChecks]=useState<boolean[]>(Array(8).fill(false)),[messages,setMessages]=useState<{role:"bot"|"user",text:string}[]>([{role:"bot",text:"Chào bạn! Hãy kể điều đang xảy ra. Mình sẽ tìm dấu hiệu rủi ro và hướng dẫn bước an toàn tiếp theo.\n\nĐừng gửi OTP, mật khẩu, PIN, CVV hoặc CCCD đầy đủ."}]),[activeCase,setActiveCase]=useState<Scam|null>(null),[loading,setLoading]=useState(false),[userId]=useState(getUserId),[sessionId]=useState(()=>createId("SESSION")),[quizIndex,setQuizIndex]=useState(0),[quizScore,setQuizScore]=useState(0),[quizChoice,setQuizChoice]=useState<number|null>(null),[quizFinished,setQuizFinished]=useState(false);const filtered=useMemo(()=>scams.filter(s=>(group==="Tất cả"||s.group===group)&&norm([s.title,s.desc,...s.keys].join(" ")).includes(norm(query))),[group,query]);const count=checks.filter(Boolean).length;async function send(e?:FormEvent,preset?:string){
  e?.preventDefault();
  const v=(preset??input).trim();
  if(!v||loading)return;
  const startedAt=Date.now();
  const isFirst=!messages.some(m=>m.role==="user");
  const matchedCase=isFirst?strongLocalCase(v):null;
  const conversationCase=activeCase??matchedCase;
  const fallback=conversationCase?answerFromCase(conversationCase,v):analyze(v);
  const useLocalFirst=isFirst&&Boolean(matchedCase);
  const useLocalFollowup=!isFirst&&Boolean(activeCase)&&caseCoversFollowup(activeCase!,v);
  setMessages(m=>[...m,{role:"user",text:v}]);
  setInput("");
  if(matchedCase)setActiveCase(matchedCase);
  if(useLocalFirst||useLocalFollowup){
    setMessages(m=>[...m,{role:"bot",text:fallback}]);
    void recordLog({user:userId,sessionId,input:v,answer:fallback,responseTimeMs:Date.now()-startedAt,source:"45_cases",caseTitle:conversationCase?.title,status:"success"});
    return;
  }
  setLoading(true);
  try{
    const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:v,context:conversationCase?caseContext(conversationCase):contextFor(v),history:messages.slice(-6).map(m=>({role:m.role==="bot"?"assistant":"user",content:m.text}))})});
    const data=await response.json().catch(()=>({}));
    const answer=response.ok&&typeof data.answer==="string"?data.answer:fallback;
    setMessages(m=>[...m,{role:"bot",text:answer}]);
    void recordLog({user:userId,sessionId,input:v,answer,responseTimeMs:Date.now()-startedAt,source:response.ok?(data.source||"gemini"):"fallback",caseTitle:conversationCase?.title,model:data.model,status:response.ok?"success":"api_error"});
  }catch{
    setMessages(m=>[...m,{role:"bot",text:fallback}]);
    void recordLog({user:userId,sessionId,input:v,answer:fallback,responseTimeMs:Date.now()-startedAt,source:"fallback",caseTitle:conversationCase?.title,status:"network_error"});
  }finally{
    setLoading(false);
  }
}function answerQuiz(choice:number){
  if(quizChoice!==null||quizFinished)return;
  setQuizChoice(choice);
  if(choice===quizData[quizIndex].correct)setQuizScore(score=>score+1);
  setTimeout(()=>{
    if(quizIndex===quizData.length-1){setQuizFinished(true);setQuizIndex(quizData.length)}
    else{setQuizIndex(index=>index+1);setQuizChoice(null)}
  },1800);
}function resetQuiz(){setQuizIndex(0);setQuizScore(0);setQuizChoice(null);setQuizFinished(false)}
function open(preset?:string){setChat(true);if(preset)setTimeout(()=>send(undefined,preset),50)}return <main>
<nav><a className="brand" href="#top"><b>S</b><span>SAFE<em>CLICK</em></span></a><div className="links"><a href="#handbook">Sổ tay</a><a href="#stories">Tình huống</a><a href="#quiz">Quiz</a><a href="#lookup">45 case</a><a href="#urgent">Khẩn cấp</a></div><button onClick={()=>open()}>💬 Hỏi trợ lý</button></nav>
<section className="hero" id="top"><div><label>● SỔ TAY AN TOÀN DÀNH CHO SINH VIÊN</label><h1>Cảnh giác trước khi<br/><em>quá muộn.</em></h1><p>Một tin nhắn, đường link hay lời mời “quá tốt để là thật” có thể là khởi đầu của một vụ lừa đảo. Dừng lại và kiểm tra trước khi hành động.</p><div className="actions"><button onClick={()=>open()}>Kể tình huống của bạn →</button><a href="#urgent">Tôi đã chuyển tiền</a></div><small>✓ Không yêu cầu thông tin bí mật　 ✓ Không phán xét　 ✓ Hướng dẫn cụ thể</small></div><div className="phone"><div className="phone-head">●　<b>Kiểm tra tình huống</b>　•••</div><p>Có người tự xưng ngân hàng yêu cầu em đọc mã OTP...</p><section><strong>!</strong><span><small>MỨC ĐỘ RỦI RO</small><b>Nguy cơ cao</b></span></section><h4>3 dấu hiệu đáng ngờ</h4><i>✓ Yêu cầu OTP</i><i>✓ Tạo áp lực thời gian</i><i>✓ Giả danh tổ chức</i></div></section>
<div className="stats"><div><b>45</b><span>Case trong chatbot</span></div><div><b>6</b><span>Nhóm nội dung sổ tay</span></div><div><b>3</b><span>Bước tự bảo vệ</span></div></div>
<section className="handbook" id="handbook">
  <header><label>SỔ TAY ĐIỆN TỬ ULIS SAFECLICK</label><h2>Ba bước để lấy lại quyền chủ động</h2><p>Dùng quy trình này trước, trong hoặc ngay sau một tình huống đáng ngờ.</p></header>
  <div className="safety-flow">
    <article><span>01</span><b>Dừng lại</b><p>Không chuyển tiền, không bấm link, không đọc OTP, không gửi giấy tờ và không cài ứng dụng.</p></article>
    <article><span>02</span><b>Kiểm chứng</b><p>Đóng tin nhắn. Tự gõ website chính thức và tự gọi số công khai, không dùng kênh người lạ cung cấp.</p></article>
    <article><span>03</span><b>Kết nối hỗ trợ</b><p>Nói với người thân, bạn bè, giảng viên, Nhà trường, ngân hàng hoặc công an tùy tình huống.</p></article>
  </div>
  <aside><b>Checklist 60 giây</b><span>0–10s: không trả lời ngay</span><span>10–30s: dừng tiền, tài khoản và thiết bị</span><span>30–60s: mở nguồn chính thức hoặc gọi người tin cậy</span></aside>
</section>
<section className="story-section" id="stories">
  <header><label>SÁU NHÓM TÌNH HUỐNG</label><h2>Bạn đang gặp chuyện gì?</h2><p>Chọn nhóm gần nhất để xem câu chuyện, dấu hiệu đỏ và hành động đầu tiên an toàn.</p></header>
  <div className="story-grid">
    {[
      ["01","Giả danh","Công an, Nhà trường, shipper, ngân hàng","Có người tự xưng công an yêu cầu giữ bí mật và chuyển tiền."],
      ["02","Học tập","Học bổng, trao đổi, du học, học phí","Email học bổng có logo yêu cầu đóng phí giữ suất hôm nay."],
      ["03","Việc làm","Gia sư, cộng tác viên, phí nhận việc","Lớp gia sư lương tốt nhưng phải chuyển phí trước."],
      ["04","Nhà trọ","Phòng giá rẻ, đặt cọc, hợp đồng","Người đăng không cho xem phòng nhưng giục đặt cọc ngay."],
      ["05","Mua bán","Vé, đồ cũ, giao hàng, link hoàn tiền","Người bán gửi link hoàn tiền và yêu cầu đăng nhập ngân hàng."],
      ["06","Tài chính","OTP, vay app, đầu tư, nhiệm vụ nạp tiền","Ứng dụng nhiệm vụ yêu cầu nạp thêm để được rút tiền."]
    ].map(x=><article key={x[0]}><span>{x[0]}</span><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p><button onClick={()=>open(x[3])}>Hỏi chatbot về tình huống này →</button></article>)}
  </div>
</section>
<section className="mini-quiz quiz-carousel" id="quiz">
  <header className="quiz-head"><div><label>QUIZ TÌNH HUỐNG</label><h2>Bạn sẽ làm gì?</h2></div><div className="quiz-meta"><b>{quizFinished?quizData.length:quizIndex+1}/{quizData.length}</b><span>Điểm: {quizScore}</span></div></header>
  <div className="quiz-progress"><i style={{width:`${(quizFinished?100:(quizIndex+1)/quizData.length*100)}%`}}/></div>
  <div className="quiz-viewport"><div className="quiz-track" style={{transform:`translateX(-${quizIndex*100}%)`}}>
    {quizData.map((q,qi)=><article className="quiz-slide" key={q.tag} aria-hidden={qi!==quizIndex}>
      <small>{q.tag}</small><h3>{q.question}</h3>
      <div className="quiz-options">{q.answers.map((answer,ai)=>{const answered=qi===quizIndex&&quizChoice!==null;const state=answered?(ai===q.correct?"right":ai===quizChoice?"wrong":""):"";return <button className={state} disabled={qi!==quizIndex||quizChoice!==null} onClick={()=>answerQuiz(ai)} key={answer}><b>{String.fromCharCode(65+ai)}</b>{answer}</button>})}</div>
      <div className={`quiz-feedback ${qi===quizIndex&&quizChoice!==null?"show":""}`}><b>{quizChoice===q.correct?"Chính xác!":"Chưa đúng."}</b><span>{q.explain}</span><em>Tự chuyển sang câu tiếp theo…</em></div>
    </article>)}
    <article className="quiz-slide quiz-result"><span>✓</span><h3>Hoàn thành!</h3><p>Bạn trả lời đúng <b>{quizScore}/{quizData.length}</b> câu.</p><small>{quizScore===quizData.length?"Rất tốt — bạn đã nhận diện đúng mọi tình huống.":"Hãy thử lại để ghi nhớ cách xử lý an toàn."}</small><button onClick={resetQuiz}>Làm lại quiz</button></article>
  </div></div>
  <div className="quiz-dots">{quizData.map((q,i)=><i className={i<quizIndex?"done":i===quizIndex?"active":""} key={q.tag}/>)}</div>
</section>
<section className="content" id="lookup"><header><div><label>KHO TÌNH HUỐNG</label><h2>Bạn đang lo lắng về điều gì?</h2><p>Tra cứu 45 tình huống thực tế theo ngôn ngữ sinh viên.</p></div><input placeholder="Tìm: nhà trọ, OTP, việc làm..." value={query} onChange={e=>setQuery(e.target.value)}/></header><div className="filters">{groups.map(g=><button className={g===group?"active":""} key={g} onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="grid">{filtered.slice(0,9).map(s=><article key={s.title} onClick={()=>setSelected(s)}><span>{s.icon}</span><small>{s.group}</small><h3>{s.title}</h3><p>{s.desc}</p><b>Xem dấu hiệu & cách xử lý　↗</b></article>)}</div>{filtered.length>9&&<p className="note">Đang hiển thị 9/{filtered.length} kết quả. Dùng bộ lọc hoặc tìm kiếm để xem nhóm cụ thể.</p>}</section>
<section className="checker" id="check"><div><label>KIỂM TRA TRONG 30 GIÂY</label><h2>Có điều gì đó<br/>không ổn?</h2><p>Đánh dấu những điều xuất hiện. Đây là sàng lọc ban đầu, không phải kết luận điều tra.</p><aside><small>KẾT QUẢ TẠM THỜI</small><b>{count===0?"Chưa chọn dấu hiệu":count===1?"Cần xác minh thêm":count<=3?"Có dấu hiệu đáng ngờ":"Nguy cơ cao — dừng lại"}</b><span>{count}/8 dấu hiệu</span></aside></div><div className="checklist">{["Yêu cầu chuyển tiền, đặt cọc hoặc phí trước","Xin OTP, mật khẩu, mã SMS hoặc thông tin thẻ","Gửi link lạ hoặc yêu cầu cài ứng dụng","Thúc giục làm ngay hoặc đe dọa","Yêu cầu giữ bí mật với người thân","Tài khoản nhận tiền là tài khoản cá nhân","Lợi ích, lương hoặc giá quá hấp dẫn","Không cho tự xác minh qua kênh chính thức"].map((x,i)=><button className={checks[i]?"on":""} key={x} onClick={()=>setChecks(c=>c.map((v,j)=>j===i?!v:v))}><i>✓</i>{x}</button>)}<button className="analyze" onClick={()=>open(`Tình huống của em có ${count} dấu hiệu trong checklist. Em cần làm gì?`)}>Phân tích kỹ hơn với trợ lý →</button></div></section>
<section className="content urgent" id="urgent"><header><div><label>XỬ LÝ KHẨN CẤP</label><h2>Bạn đã thực hiện thao tác?</h2><p>Đừng hoảng loạn. Ưu tiên giảm thiệt hại theo đúng thứ tự.</p></div></header><div className="steps">{[["01","Dừng ngay","Dừng chuyển tiền, liên lạc, bấm link và cài app."],["02","Gọi ngân hàng","Dùng số chính thức để khóa giao dịch và tra soát."],["03","Bảo vệ tài khoản","Đổi mật khẩu an toàn, đăng xuất phiên lạ, bật 2FA."],["04","Lưu bằng chứng","Giữ tin nhắn, URL, tài khoản nhận và biên lai."],["05","Trình báo","Liên hệ Công an khi mất tiền, bị đe dọa hoặc cài mã độc."],["06","Cảnh giác lần hai","Không nộp phí cho dịch vụ hứa lấy lại tiền."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="danger"><b>Đã cài app lạ hoặc bật quyền Trợ năng?</b><span>Ngắt mạng thiết bị, không mở app ngân hàng và liên hệ ngân hàng ngay.</span><button onClick={()=>open("Em đã cài app lạ và bật quyền Trợ năng, giờ phải làm gì?")}>Mở hướng dẫn</button></div></section>
<section className="promo"><b>✦</b><div><label>TRỢ LÝ TÌNH HUỐNG</label><h2>Bạn không cần biết tên loại lừa đảo.</h2><p>Chỉ cần kể điều đã xảy ra. Trợ lý sẽ tìm dấu hiệu, hỏi thêm và hướng dẫn xử lý an toàn.</p></div><button onClick={()=>open()}>Bắt đầu trò chuyện →</button></section>
<footer><div className="brand"><b>S</b><span>SAFE<em>STUDENT</em></span></div><p>Dừng lại · Xác minh · Bảo vệ tài khoản · Lưu bằng chứng · Trình báo khi cần</p><small>Công cụ hỗ trợ nhận diện, không thay thế kết luận của cơ quan chức năng.</small></footer>
{selected&&<div className="backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><span>{selected.icon}</span><small>{selected.group}</small><h2>{selected.title}</h2><p>{selected.desc}</p><h4>Dấu hiệu cần chú ý</h4><ul>{selected.signs.map(x=><li key={x}>✓ {x}</li>)}</ul><blockquote>“{selected.example}”</blockquote><aside><b>Nên làm ngay</b><p>{selected.action}</p></aside><button className="full" onClick={()=>{setSelected(null);open(selected.example)}}>Tình huống này giống tôi →</button></div></div>}
<button className="fab" onClick={()=>setChat(v=>!v)}>{chat?"×":"💬"}</button>{chat&&<aside className="chat"><header><b>✦　Trợ lý SafeStudent</b><button onClick={()=>setChat(false)}>—</button></header><small>🔒 Không gửi OTP, mật khẩu, PIN, CVV hoặc CCCD đầy đủ.</small><div className="messages">{messages.map((m,i)=><p className={m.role} key={i}>{m.text}</p>)}{loading&&<p className="bot">Đang phân tích tình huống…</p>}</div><div className="chips"><button onClick={()=>send(undefined,"Có người yêu cầu em đóng phí nhận việc")}>Phí nhận việc</button><button onClick={()=>send(undefined,"Em đã chuyển tiền rồi")}>Đã chuyển tiền</button><button onClick={()=>send(undefined,"Link này có đáng ngờ không?")}>Link lạ</button></div><form onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Kể tình huống của bạn..."/><button disabled={loading} aria-label="Gửi câu hỏi">➤</button></form></aside>}
</main>}
