"use client";
import {FormEvent,useMemo,useState} from "react";

type Scam={title:string;group:string;icon:string;desc:string;example:string;signs:string[];action:string;keys:string[]};
const S=(title:string,group:string,icon:string,desc:string,example:string,signs:string[],action:string,keys:string[]):Scam=>({title,group,icon,desc,example,signs,action,keys});
const scams:Scam[]=[
S("Giả danh nhà trường","Nhà trường","🏫","Mạo danh phòng đào tạo, công tác sinh viên hoặc tài chính để yêu cầu tiền và dữ liệu.","Phòng CTSV yêu cầu chuyển 500.000đ xác nhận hồ sơ trước 11 giờ.",["Tài khoản cá nhân","Tên miền không chính thức","Thúc giục đóng tiền"],"Không chuyển tiền; tự mở cổng sinh viên hoặc gọi số công khai của trường.",["nhà trường","học phí","nhập học","phòng đào tạo","hồ sơ"]),
S("Học bổng, trao đổi giả","Nhà trường","🎓","Thông báo trúng học bổng rồi yêu cầu phí giữ suất hoặc xác minh.","Trúng học bổng 100% nhưng phải đóng 2 triệu trong hôm nay.",["Trúng khi chưa nộp hồ sơ","Phải đóng phí trước","Không có trên website chính thức"],"Xác minh trực tiếp với đơn vị cấp học bổng; không nộp phí qua tài khoản cá nhân.",["học bổng","trao đổi","giữ suất","du học"]),
S("Việc nhẹ lương cao","Việc làm","💼","Tin tuyển dụng mơ hồ, hứa thu nhập bất thường hoặc dụ đi xa.","Tuyển đánh máy 500.000đ/ngày, có xe đón đi nhận việc.",["Không rõ pháp nhân","Lương cao bất thường","Yêu cầu đi xa/giữ giấy tờ"],"Không đi theo người lạ; kiểm tra doanh nghiệp, địa chỉ và báo người thân.",["việc nhẹ","lương cao","tuyển dụng","part-time","đánh máy"]),
S("Nhiệm vụ online, CTV","Việc làm","📲","Nạp tiền làm nhiệm vụ, được hoàn khoản nhỏ rồi bị ép nạp ngày càng lớn.","Nạp 200.000đ được hoàn 260.000đ, sau đó bị bắt nạp 3 triệu.",["Nạp tiền để nhận việc","Rút tiền phải nộp thêm","Cam kết hoàn vốn nhanh"],"Dừng nạp ngay; không vay tiền; lưu nhóm chat và giao dịch.",["nhiệm vụ","cộng tác viên","chốt đơn","hoa hồng","telegram","nạp tiền"]),
S("Nhà trọ, đặt cọc phòng","Nhà ở","🏠","Đăng phòng đẹp giá rẻ rồi thúc giục cọc trước khi xem và xác minh.","Chủ nhà ở tỉnh khác, yêu cầu cọc 1 triệu để giữ phòng.",["Không cho xem phòng","Giá thấp bất thường","Tài khoản khác tên chủ nhà"],"Không cọc trước khi xem; xác minh người cho thuê và hợp đồng.",["phòng trọ","nhà trọ","đặt cọc","giữ phòng","chủ nhà"]),
S("Mua bán online giá rẻ","Mua sắm","🛒","Rao hàng không tồn tại hoặc sai mô tả và đòi thanh toán toàn bộ trước.","Laptop cũ rẻ hơn 40%, người bán bắt trả hết rồi mới gửi.",["Chỉ nhận chuyển khoản trước","Từ chối gặp/COD","Tài khoản mới lập"],"Ưu tiên gặp trực tiếp hoặc nền tảng bảo vệ người mua.",["mua hàng","laptop","marketplace","cod","giá rẻ"]),
S("Vé và booking giả","Mua sắm","🎟️","Bán vé concert, máy bay hoặc booking giả; một QR có thể bán nhiều lần.","Người bán gửi ảnh QR vé concert rồi giục chuyển ngay.",["Chỉ có ảnh QR","Không chuyển nhượng chính thức","Giá rẻ bất thường"],"Mua qua nền tảng chính thức và tự xác minh mã đặt chỗ.",["vé concert","vé máy bay","booking","qr vé","vé giả"]),
S("Giả danh ngân hàng","Tài chính","🏦","Dọa khóa tài khoản rồi xin OTP, mật khẩu hoặc tiền xác minh.","Người gọi tự xưng ngân hàng yêu cầu đọc OTP mở khóa.",["Xin OTP/PIN/CVV","Bắt mở app khi gọi","Tài khoản an toàn"],"Ngắt cuộc gọi; tự gọi số ngân hàng chính thức; không cung cấp OTP.",["ngân hàng","otp","khóa tài khoản","cvv","tài khoản an toàn"]),
S("Giả danh Công an, Tòa án","Mạo danh","⚖️","Cáo buộc liên quan vụ án để tạo sợ hãi rồi đòi tiền hoặc yêu cầu giữ bí mật.","Tự xưng Công an, nói liên quan rửa tiền và phải chuyển tiền kiểm tra.",["Chuyển tiền chứng minh vô tội","Giữ bí mật","Gửi app/link lạ"],"Kết thúc cuộc gọi; báo người thân và tự xác minh với cơ quan Công an.",["công an","tòa án","viện kiểm sát","rửa tiền","lệnh bắt"]),
S("Phishing: link, email giả","An toàn số","🎣","Website hoặc email giả trường, ngân hàng, mạng xã hội để đánh cắp tài khoản.","Email nói Microsoft trường sắp khóa nếu không đăng nhập qua link.",["Tên miền gần giống","Đòi đăng nhập gấp","Xin dữ liệu nhạy cảm"],"Không bấm link; tự gõ địa chỉ chính thức; đổi mật khẩu nếu đã nhập.",["link","email","website","phishing","đăng nhập","microsoft"]),
S("Chiếm tài khoản, mượn tiền","Mạng xã hội","👤","Chiếm Facebook/Zalo rồi nhắn người quen mượn tiền gấp.","Bạn thân nhắn Messenger mượn 5 triệu nhưng gọi không nghe.",["Cách nói khác thường","Né gọi trực tiếp","Giục chuyển gấp"],"Xác minh qua số điện thoại hoặc người thân trước khi chuyển.",["facebook","zalo","messenger","mượn tiền","bạn thân"]),
S("Giả shipper, hoàn tiền","Mua sắm","📦","Giả shipper hoặc nhân viên sàn rồi dựng chuyện hội viên, hoàn tiền.","Chuyển 20.000đ phí giao hàng rồi bị đòi tiền hủy hội viên.",["Biết một phần đơn hàng","Chuyển ngoài sàn","Phí hủy/hoàn tiền"],"Dừng chuyển; tự liên hệ sàn hoặc đơn vị vận chuyển chính thức.",["shipper","giao hàng","hoàn tiền","hội viên","phí ship"]),
S("QR code giả","An toàn số","▦","QR dẫn tới website giả hoặc bị dán đè lên mã thanh toán thật.","Quét QR nhận quà, trang mở ra yêu cầu đăng nhập Facebook.",["QR không rõ nguồn","Đòi đăng nhập","Tên miền lạ"],"Đóng trang, kiểm tra URL và tìm kênh chính thức.",["qr","quét mã","nhận quà","mã qr"]),
S("Ứng dụng giả, mã độc","An toàn số","📱","Dụ cài APK/app giả rồi bật Trợ năng, đọc SMS hoặc điều khiển màn hình.","Người tự xưng cán bộ gửi app VNeID và yêu cầu bật Trợ năng.",["Cài app ngoài kho","Bật Trợ năng","Chia sẻ màn hình"],"Ngắt mạng thiết bị; liên hệ ngân hàng; đổi thông tin từ thiết bị an toàn.",["apk","app lạ","vneid","trợ năng","anydesk","teamviewer"]),
S("Vay online, phí giải ngân","Tài chính","💳","Báo khoản vay bị đóng băng rồi đòi phí mở khóa trước giải ngân.","App vay báo sai số tài khoản, phải chuyển 3 triệu mở khóa.",["Phí trước giải ngân","Khoản vay đóng băng","Đơn vị mơ hồ"],"Không chuyển thêm; kiểm tra tổ chức cho vay và lưu hồ sơ.",["vay online","giải ngân","mở khóa khoản vay","app vay"]),
S("Đầu tư, crypto, forex giả","Tài chính","📈","Cam kết lãi cao, cho rút nhỏ rồi khóa tiền và đòi thuế/phí.","Đầu tư 5 triệu; khi rút 20 triệu bị đòi thêm 5 triệu thuế.",["Lợi nhuận cố định cao","Rút phải nộp thêm","Nhóm chuyên gia gây áp lực"],"Dừng nạp; gọi ngân hàng; lưu bằng chứng và trình báo.",["đầu tư","crypto","forex","sàn","lợi nhuận","rút tiền"]),
S("Trúng thưởng, quà giả","Mua sắm","🎁","Báo trúng quà lớn rồi đòi thuế, phí ship hoặc thông tin thẻ.","Trúng iPhone nhưng phải chuyển 700.000đ tiền thuế.",["Trúng khi không tham gia","Nộp phí trước","Xin thông tin thẻ"],"Không chuyển phí; xác minh trên kênh chính thức của thương hiệu.",["trúng thưởng","quà tặng","iphone","khuyến mại"]),
S("Lừa đảo tình cảm","Mạng xã hội","💔","Tạo quan hệ qua mạng rồi mượn tiền, rủ đầu tư hoặc dựng chuyện quà.","Người quen online gửi quà từ Mỹ, sau đó đòi 8 triệu phí hải quan.",["Quan hệ tiến triển quá nhanh","Biến cố bất ngờ","Liên tục phát sinh phí"],"Không chuyển tiền; xác minh độc lập danh tính và câu chuyện.",["tình cảm","quen online","quà nước ngoài","hải quan"]),
S("Deepfake người thân","Mạo danh","🎭","Dùng AI giả giọng/video người thân, giảng viên để xin tiền khẩn cấp.","Video call giống anh trai nói đang cấp cứu, cần 10 triệu ngay.",["Tình huống rất khẩn","Né câu hỏi riêng","Tài khoản nhận lạ"],"Gọi lại số quen và hỏi điều chỉ người thật biết.",["deepfake","giả giọng","video call","người thân","cấp cứu"]),
S("Bắt cóc online, tống tiền","Mạo danh","🚨","Ép nạn nhân tự cô lập, không liên hệ gia đình và quay video.","Tự xưng Công an, bắt vào khách sạn, tắt máy với gia đình.",["Ép tự cô lập","Cấm nói với gia đình","Đe dọa/quay video"],"Không tự cô lập; liên hệ ngay người thân và Công an gần nhất.",["bắt cóc online","khách sạn","cô lập","tống tiền","giữ bí mật"]),
S("Từ thiện giả","Mạng xã hội","🤲","Dùng chuyện thương tâm hoặc mạo danh tổ chức để kêu gọi tiền.","Bài hỗ trợ sinh viên tai nạn vào tài khoản cá nhân nhưng trường không thông báo.",["Không có nguồn xác nhận","Fanpage mới","Tài khoản cá nhân"],"Xác minh qua trường/tổ chức; chỉ ủng hộ qua kênh minh bạch.",["từ thiện","kêu gọi","donation","tai nạn","ủng hộ"]),
S("Đánh cắp CCCD, dữ liệu","An toàn số","🪪","Thu thập CCCD, khuôn mặt và mã xác thực để mở tài khoản hoặc vay.","Nhà tuyển dụng xin CCCD hai mặt và selfie qua Telegram.",["Xin dữ liệu quá mức","Gửi qua tài khoản cá nhân","Xin thêm OTP"],"Xác minh đơn vị; không gửi OTP; hạn chế dữ liệu không cần thiết.",["cccd","selfie","dữ liệu cá nhân","định danh"])
];
const groups=["Tất cả","Nhà trường","Việc làm","Nhà ở","Tài chính","Mua sắm","Mạng xã hội","An toàn số","Mạo danh"];
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function analyze(input:string){const t=norm(input);const incident=/da chuyen|da nap|da nhap|da doc otp|da cai|mat tien/.test(t);const signs:string[]=[];if(/otp|mat khau|password|pin|cvv/.test(t))signs.push("thông tin bí mật/OTP");if(/chuyen tien|dat coc|nop phi|nap tien/.test(t))signs.push("chuyển tiền, cọc hoặc phí trước");if(/apk|app la|tro nang|anydesk|chia se man hinh/.test(t))signs.push("app hoặc quyền bất thường");if(/gap|ngay|hom nay|khoa tai khoan|lenh bat/.test(t))signs.push("áp lực thời gian/đe dọa");if(/giu bi mat|khong noi|co lap|khach san/.test(t))signs.push("giữ bí mật hoặc cô lập");const ranked=scams.map(s=>({s,n:s.keys.filter(k=>t.includes(norm(k))).length})).sort((a,b)=>b.n-a.n);const hit=ranked[0].n?ranked[0].s:null;if(incident)return `MỨC ĐỘ: NGUY CƠ CAO\n\nBạn cho biết sự việc đã xảy ra. Hãy ưu tiên giảm thiệt hại:\n1. Dừng mọi giao dịch và liên lạc.\n2. Gọi ngân hàng qua số chính thức để khóa/hạn chế giao dịch và tra soát.\n3. Nếu cài app lạ, ngắt mạng và không mở app ngân hàng trên thiết bị đó.\n4. Đổi mật khẩu từ thiết bị an toàn, đăng xuất phiên lạ, bật 2FA.\n5. Lưu tin nhắn, URL, tài khoản, biên lai; trình báo Công an khi cần.\n\nKhông nộp thêm phí cho dịch vụ hứa lấy lại tiền.`;if(signs.length)return `MỨC ĐỘ: NGUY CƠ CAO\n\nNhóm gần nhất: ${hit?.title||"Chưa xác định"}.\nDấu hiệu: ${signs.join(", ")}.\n\nLàm ngay:\n1. Dừng chuyển tiền, không bấm link/cài app.\n2. Không cung cấp OTP, mật khẩu, PIN, CVV.\n3. Tự tìm kênh chính thức để xác minh.${hit?`\n\n${hit.action}`:""}`;if(hit)return `MỨC ĐỘ: CÓ DẤU HIỆU ĐÁNG NGỜ\n\nCó thể liên quan: ${hit.title}.\n${hit.desc}\n\nCần biết thêm:\n1. Họ có yêu cầu tiền trước không?\n2. Có link hoặc app lạ không?\n3. Bạn đã tự xác minh chưa?`;return "MỨC ĐỘ: CHƯA ĐỦ THÔNG TIN\n\nHãy kể người đó yêu cầu bạn làm gì, có tiền/OTP/link/app lạ không và bạn đã thực hiện bước nào. Không gửi OTP, mật khẩu, PIN, CVV hoặc CCCD đầy đủ."}

export default function Home(){const[group,setGroup]=useState("Tất cả"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Scam|null>(null),[chat,setChat]=useState(false),[input,setInput]=useState(""),[checks,setChecks]=useState<boolean[]>(Array(8).fill(false)),[messages,setMessages]=useState<{role:"bot"|"user",text:string}[]>([{role:"bot",text:"Chào bạn! Hãy kể điều đang xảy ra. Mình sẽ tìm dấu hiệu rủi ro và hướng dẫn bước an toàn tiếp theo.\n\nĐừng gửi OTP, mật khẩu, PIN, CVV hoặc CCCD đầy đủ."}]);const filtered=useMemo(()=>scams.filter(s=>(group==="Tất cả"||s.group===group)&&norm([s.title,s.desc,...s.keys].join(" ")).includes(norm(query))),[group,query]);const count=checks.filter(Boolean).length;function send(e?:FormEvent,preset?:string){e?.preventDefault();const v=(preset??input).trim();if(!v)return;setMessages(m=>[...m,{role:"user",text:v},{role:"bot",text:analyze(v)}]);setInput("")}function open(preset?:string){setChat(true);if(preset)setTimeout(()=>send(undefined,preset),50)}return <main>
<nav><a className="brand" href="#top"><b>S</b><span>SAFE<em>STUDENT</em></span></a><div className="links"><a href="#lookup">Tra cứu</a><a href="#check">Kiểm tra nhanh</a><a href="#urgent">Khẩn cấp</a></div><button onClick={()=>open()}>💬 Hỏi trợ lý</button></nav>
<section className="hero" id="top"><div><label>● SỔ TAY AN TOÀN DÀNH CHO SINH VIÊN</label><h1>Cảnh giác trước khi<br/><em>quá muộn.</em></h1><p>Một tin nhắn, đường link hay lời mời “quá tốt để là thật” có thể là khởi đầu của một vụ lừa đảo. Dừng lại và kiểm tra trước khi hành động.</p><div className="actions"><button onClick={()=>open()}>Kể tình huống của bạn →</button><a href="#urgent">Tôi đã chuyển tiền</a></div><small>✓ Không yêu cầu thông tin bí mật　 ✓ Không phán xét　 ✓ Hướng dẫn cụ thể</small></div><div className="phone"><div className="phone-head">●　<b>Kiểm tra tình huống</b>　•••</div><p>Có người tự xưng ngân hàng yêu cầu em đọc mã OTP...</p><section><strong>!</strong><span><small>MỨC ĐỘ RỦI RO</small><b>Nguy cơ cao</b></span></section><h4>3 dấu hiệu đáng ngờ</h4><i>✓ Yêu cầu OTP</i><i>✓ Tạo áp lực thời gian</i><i>✓ Giả danh tổ chức</i></div></section>
<div className="stats"><div><b>22</b><span>Nhóm lừa đảo</span></div><div><b>7</b><span>Bước xử lý chung</span></div><div><b>24/7</b><span>Trợ lý tình huống</span></div></div>
<section className="content" id="lookup"><header><div><label>KHO TÌNH HUỐNG</label><h2>Bạn đang lo lắng về điều gì?</h2><p>Tra cứu 22 hình thức phổ biến theo ngôn ngữ sinh viên.</p></div><input placeholder="Tìm: nhà trọ, OTP, việc làm..." value={query} onChange={e=>setQuery(e.target.value)}/></header><div className="filters">{groups.map(g=><button className={g===group?"active":""} key={g} onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="grid">{filtered.slice(0,9).map(s=><article key={s.title} onClick={()=>setSelected(s)}><span>{s.icon}</span><small>{s.group}</small><h3>{s.title}</h3><p>{s.desc}</p><b>Xem dấu hiệu & cách xử lý　↗</b></article>)}</div>{filtered.length>9&&<p className="note">Đang hiển thị 9/{filtered.length} kết quả. Dùng bộ lọc hoặc tìm kiếm để xem nhóm cụ thể.</p>}</section>
<section className="checker" id="check"><div><label>KIỂM TRA TRONG 30 GIÂY</label><h2>Có điều gì đó<br/>không ổn?</h2><p>Đánh dấu những điều xuất hiện. Đây là sàng lọc ban đầu, không phải kết luận điều tra.</p><aside><small>KẾT QUẢ TẠM THỜI</small><b>{count===0?"Chưa chọn dấu hiệu":count===1?"Cần xác minh thêm":count<=3?"Có dấu hiệu đáng ngờ":"Nguy cơ cao — dừng lại"}</b><span>{count}/8 dấu hiệu</span></aside></div><div className="checklist">{["Yêu cầu chuyển tiền, đặt cọc hoặc phí trước","Xin OTP, mật khẩu, mã SMS hoặc thông tin thẻ","Gửi link lạ hoặc yêu cầu cài ứng dụng","Thúc giục làm ngay hoặc đe dọa","Yêu cầu giữ bí mật với người thân","Tài khoản nhận tiền là tài khoản cá nhân","Lợi ích, lương hoặc giá quá hấp dẫn","Không cho tự xác minh qua kênh chính thức"].map((x,i)=><button className={checks[i]?"on":""} key={x} onClick={()=>setChecks(c=>c.map((v,j)=>j===i?!v:v))}><i>✓</i>{x}</button>)}<button className="analyze" onClick={()=>open(`Tình huống của em có ${count} dấu hiệu trong checklist. Em cần làm gì?`)}>Phân tích kỹ hơn với trợ lý →</button></div></section>
<section className="content urgent" id="urgent"><header><div><label>XỬ LÝ KHẨN CẤP</label><h2>Bạn đã thực hiện thao tác?</h2><p>Đừng hoảng loạn. Ưu tiên giảm thiệt hại theo đúng thứ tự.</p></div></header><div className="steps">{[["01","Dừng ngay","Dừng chuyển tiền, liên lạc, bấm link và cài app."],["02","Gọi ngân hàng","Dùng số chính thức để khóa giao dịch và tra soát."],["03","Bảo vệ tài khoản","Đổi mật khẩu an toàn, đăng xuất phiên lạ, bật 2FA."],["04","Lưu bằng chứng","Giữ tin nhắn, URL, tài khoản nhận và biên lai."],["05","Trình báo","Liên hệ Công an khi mất tiền, bị đe dọa hoặc cài mã độc."],["06","Cảnh giác lần hai","Không nộp phí cho dịch vụ hứa lấy lại tiền."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="danger"><b>Đã cài app lạ hoặc bật quyền Trợ năng?</b><span>Ngắt mạng thiết bị, không mở app ngân hàng và liên hệ ngân hàng ngay.</span><button onClick={()=>open("Em đã cài app lạ và bật quyền Trợ năng, giờ phải làm gì?")}>Mở hướng dẫn</button></div></section>
<section className="promo"><b>✦</b><div><label>TRỢ LÝ TÌNH HUỐNG</label><h2>Bạn không cần biết tên loại lừa đảo.</h2><p>Chỉ cần kể điều đã xảy ra. Trợ lý sẽ tìm dấu hiệu, hỏi thêm và hướng dẫn xử lý an toàn.</p></div><button onClick={()=>open()}>Bắt đầu trò chuyện →</button></section>
<footer><div className="brand"><b>S</b><span>SAFE<em>STUDENT</em></span></div><p>Dừng lại · Xác minh · Bảo vệ tài khoản · Lưu bằng chứng · Trình báo khi cần</p><small>Công cụ hỗ trợ nhận diện, không thay thế kết luận của cơ quan chức năng.</small></footer>
{selected&&<div className="backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><span>{selected.icon}</span><small>{selected.group}</small><h2>{selected.title}</h2><p>{selected.desc}</p><h4>Dấu hiệu cần chú ý</h4><ul>{selected.signs.map(x=><li key={x}>✓ {x}</li>)}</ul><blockquote>“{selected.example}”</blockquote><aside><b>Nên làm ngay</b><p>{selected.action}</p></aside><button className="full" onClick={()=>{setSelected(null);open(selected.example)}}>Tình huống này giống tôi →</button></div></div>}
<button className="fab" onClick={()=>setChat(v=>!v)}>{chat?"×":"💬"}</button>{chat&&<aside className="chat"><header><b>✦　Trợ lý SafeStudent</b><button onClick={()=>setChat(false)}>—</button></header><small>🔒 Không gửi OTP, mật khẩu, PIN, CVV hoặc CCCD đầy đủ.</small><div className="messages">{messages.map((m,i)=><p className={m.role} key={i}>{m.text}</p>)}</div><div className="chips"><button onClick={()=>send(undefined,"Có người yêu cầu em đóng phí nhận việc")}>Phí nhận việc</button><button onClick={()=>send(undefined,"Em đã chuyển tiền rồi")}>Đã chuyển tiền</button><button onClick={()=>send(undefined,"Link này có đáng ngờ không?")}>Link lạ</button></div><form onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Kể tình huống của bạn..."/><button>➤</button></form></aside>}
</main>}
